name: local-aircrafts-webgl

services:
  # data:
  #   image: node:22-alpine
  #   env_file: .env
  #   working_dir: /app
  #   command: node dump1090-logger.js
  #   volumes:
  #     - .:/app

  web:
    image: node:22-alpine
    working_dir: /app
    command: npx http-server -d false -p 3000
    volumes:
      - .:/app
    ports:
      - 3001:3000
